name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  check-version:
    runs-on: ubuntu-20.04
    outputs:
      version_changed: ${{ steps.check.outputs.changed }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current version from repository
        id: get_version
        run: |
          # Extract the CURRENT_VERSION from the file
          CURRENT_VERSION=$(grep 'CURRENT_VERSION' src/main/java/me/t3sl4/updater/utils/SystemVariables.java | grep -oP 'v\K[0-9]+\.[0-9]+\.[0-9]+')
          # Validate the extracted version
          if [[ -z "$CURRENT_VERSION" ]]; then
            echo "Error: CURRENT_VERSION not found!"
            exit 1
          fi
          echo "Extracted CURRENT_VERSION: $CURRENT_VERSION"
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Get latest release version
        id: get_latest
        run: |
          # Fetch the latest release version from GitHub API
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hidirektor/ondergrup-updater-service/releases/latest | jq -r '.tag_name' | sed 's/v//')
          # Validate the fetched version
          if [[ -z "$LATEST_VERSION" || "$LATEST_VERSION" == "null" ]]; then
            echo "Error: LATEST_VERSION not found!"
            exit 1
          fi
          echo "Latest release version: $LATEST_VERSION"
          echo "latest=$LATEST_VERSION" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: check
        run: |
          CURRENT_VERSION="${{ steps.get_version.outputs.version }}"
          LATEST_VERSION="${{ steps.get_latest.outputs.latest }}"
          # Compare versions and set output
          if [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed! Triggering build..."
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged. Skipping build."
            echo "changed=false" >> $GITHUB_OUTPUT
          fi


  macos-build:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true'
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (MacOS)
        run: mvn clean package

      - name: Rename JAR file (MacOS)
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          mv "$JAR_FILE" macos_Updater.jar

      - name: Upload artifact (MacOS)
        uses: actions/upload-artifact@v3
        with:
          name: macos_Updater
          path: macos_Updater.jar

  unix-build:
    needs: macos-build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (Ubuntu)
        run: mvn clean package

      - name: Rename JAR file (Ubuntu)
        run: |
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          mv "$JAR_FILE" unix_Updater.jar

      - name: Upload artifact (Ubuntu)
        uses: actions/upload-artifact@v3
        with:
          name: unix_Updater
          path: unix_Updater.jar

  windows-build:
    needs: unix-build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project (Windows)
        run: |
          for i in {1..3}; do
            mvn clean package && break || sleep 10
          done
        shell: bash

      - name: Rename JAR file (Windows)
        run: |
          $JAR_FILE = Get-ChildItem -Path target -Filter *.jar | Select-Object -First 1
          Move-Item -Path $JAR_FILE.FullName -Destination ondergrup-updater-service.jar -Force

      - name: Install Launch4j (Windows)
        run: |
          Invoke-WebRequest -Uri "https://github.com/hidirektor/ondergrup-updater-service/raw/master/launch4j/launch4j-3.50-win32.exe" -OutFile "launch4j-setup.exe"
          Start-Process -FilePath "launch4j-setup.exe" -ArgumentList "/S" -NoNewWindow -Wait

      - name: Download Launch4j Config
        run: |
          Invoke-WebRequest -Uri "https://github.com/hidirektor/ondergrup-updater-service/raw/master/launch4j/ondergrup-updater-service-config.xml" -OutFile "ondergrup-updater-service-config.xml"

      - name: Check Launch4j Installation (Windows)
        run: Get-ChildItem -Path "C:\Program Files (x86)\Launch4j"

      - name: Generate EXE using Launch4j (Windows)
        run: |
          & "C:\Program Files (x86)\Launch4j\launch4jc.exe" "ondergrup-updater-service-config.xml"

      - name: Rename EXE file (Windows)
        run: mv target/*.exe windows_Updater.exe

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v3
        with:
          name: windows_Updater
          path: windows_Updater.exe

  release:
    needs: [macos-build, unix-build, windows-build]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine next version
        id: version
        run: |
          CURRENT_VERSION=$(curl -s https://raw.githubusercontent.com/hidirektor/ondergrup-updater-service/master/src/main/java/me/t3sl4/updater/utils/SystemVariables.java | grep 'CURRENT_VERSION' | sed -E 's/.*"v([0-9]+\.[0-9]+\.[0-9]+)".*/\1/')
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          NEXT_VERSION="$MAJOR.$MINOR.$((PATCH))"
          echo "version=$NEXT_VERSION" >> $GITHUB_ENV

      - name: Download all artifacts
        uses: actions/download-artifact@v3

      - name: Prepare artifacts for release
        run: |
          mkdir -p artifacts
          mv macos_Updater/macos_Updater.jar artifacts/
          mv unix_Updater/unix_Updater.jar artifacts/
          mv windows_Updater/windows_Updater.exe artifacts/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.version }}
          name: v${{ env.version }} - Yeniliklerle Dolu Bir Deneyim! 🚀
          body: |
            Sevgili kullanıcılarımız,
            
              Bu güncelleme ile uygulamamızı daha güçlü, daha hızlı ve daha kullanıcı dostu hale getirdik. İşte sizler için sunduğumuz yenilikler:
            
              ✨ Yeni Özellikler:
              - Performans Artışı: Daha hızlı yüklenme süreleri ve optimize edilmiş işlem kapasitesi.
              - Yeni Arayüz Tasarımı: Modern ve minimalist tasarım ile daha sezgisel bir kullanıcı deneyimi.
              - Gelişmiş Bildirim Sistemi: Önemli güncellemelerden anında haberdar olun.
            
              🔧 Hata Düzeltmeleri ve İyileştirmeler:
              - Küçük hatalar giderildi ve genel sistem kararlılığı artırıldı.
              - Geri bildirimlerinizi dikkate alarak kullanıcı deneyimini geliştirdik.
            
              💡 Yeni Eklenen Özellikler:
              - Karanlık Mod: Göz dostu bir deneyim için karanlık tema seçeneği eklendi.
              - Çoklu Dil Desteği: Artık birden fazla dilde hizmet sunuyoruz!
            
              Bize destek olduğunuz için teşekkür ederiz. Sizlerin geri bildirimleriyle her geçen gün daha iyiye gidiyoruz. Yeni sürümümüzü hemen keşfedin!
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.SETUP_TOKEN }}